#!/usr/bin/env python

import bootstrap


def main():
    """Destroy any resources accociated with guests"""

    hypervisor = bootstrap.HypervisorClient('localhost')

    bootstrap.info('Deleting hosts ...')
    hosts = hypervisor.host_list()
    for host in hosts:
        bootstrap.detail(host['name'])
        hypervisor.host_delete(host['name'])

    bootstrap.info('Deleting networks ...')
    networks = hypervisor.network_list()
    for network in networks:
        bootstrap.detail(network['name'])
        hypervisor.network_delete(network['name'])


if __name__ == '__main__':
    main()


# vi: ts=4 et:
