#!/bin/bash

# Allow root login while we set things up.  We can't have a local account as our puppet
# code stupidly uses hard coded UIDs and GIDs because we're obviously living in the
# 1970s and program mainframes.  This will be fixed up when actual puppet code runs
sed -i 's/^PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
